"""Keep snk's winding route, then grow its snake as real cells are eaten."""
from pathlib import Path
import re
import sys

svg_path = Path(sys.argv[1])
svg = svg_path.read_text(encoding="utf-8")
if "Generated with https://github.com/Platane/snk" not in svg:
    raise SystemExit("Expected an SVG generated by Platane/snk")

eaten_times = sorted(
    float(match.group(1))
    for match in re.finditer(
        r"@keyframes c[0-9a-z]+\{[^}]*\}([0-9.]+)%,100%\{fill:var\(--ce\)\}",
        svg,
    )
)
tail_style = re.search(
    r"\.s\.s3\{transform:(translate\([^}]+\));animation-name:s3\}", svg
)
tail_rect = re.search(r'<rect class="s s3"[^>]*/>', svg)
if not eaten_times or not tail_style or not tail_rect:
    raise SystemExit("Could not find snk's food events and four-part snake")

growth_count = min(6, len(eaten_times))
growth_times = [
    eaten_times[max(0, round(len(eaten_times) * (index + 1) /
                             (growth_count + 1)) - 1)]
    for index in range(growth_count)
]
colors = ["#facc15", "#f59e0b", "#fb923c", "#e8798d",
          "#c26bb3", "#9b5dc4", "#7c3aed"]

for segment in range(4):
    old = f"animation-name:s{segment}}}"
    new = f"animation-name:s{segment},snakeColor;" \
          f"animation-timing-function:linear,steps(1,end)}}"
    if old not in svg:
        raise SystemExit(f"Missing snake segment {segment}")
    svg = svg.replace(old, new, 1)

css = []
color_frames = [f"0%{{fill:{colors[0]}}}"]
for index, moment in enumerate(growth_times):
    color_frames.append(f"{moment:.2f}%{{fill:{colors[round((index + 1) * 6 / growth_count)]}}}")
color_frames.append(f"100%{{fill:{colors[6]}}}")
css.append("@keyframes snakeColor{" + "".join(color_frames) + "}")

new_segments = []
for index, moment in enumerate(growth_times):
    number = index + 4
    before = max(0.0, moment - .02)
    after = min(100.0, moment + .02)
    css.append(
        f"@keyframes grow{number}{{"
        f"0%,{before:.2f}%{{opacity:0}}"
        f"{after:.2f}%,100%{{opacity:1}}"
        f"}}.s.g{number}{{transform:{tail_style.group(1)};"
        f"animation-name:s3,snakeColor,grow{number};"
        f"animation-delay:{(index + 1) * 100}ms,0ms,0ms;"
        f"animation-timing-function:linear,steps(1,end),steps(1,end)}}"
    )
    new_segments.append(
        tail_rect.group().replace('class="s s3"', f'class="s g{number}"')
    )
svg = svg.replace("</style>", "".join(css) + "</style>", 1)
svg = svg.replace('<rect class="s s0"', "".join(new_segments) +
                  '<rect class="s s0"', 1)
svg_path.write_text(svg, encoding="utf-8")
print(f"Growing from 4 to {4 + growth_count} cells after "
      f"{len(eaten_times)} real contribution cells are eaten")
