"""Add a color-changing snake and contribution-eating highlights to snk's SVG."""
from pathlib import Path
import re
import sys

svg_path = Path(sys.argv[1])
svg = svg_path.read_text(encoding="utf-8")
if "Generated with https://github.com/Platane/snk" not in svg:
    raise SystemExit("Expected an SVG generated by Platane/snk")

eaten = {
    match.group(1): float(match.group(2))
    for match in re.finditer(
        r"@keyframes (c[0-9a-z]+)\{[^}]*\}([0-9.]+)%,100%\{fill:var\(--ce\)\}",
        svg,
    )
}
cells = [
    (eaten[match.group(1)], float(match.group(2)) + 6, float(match.group(3)) + 6)
    for match in re.finditer(
        r'<rect class="c (c[0-9a-z]+)" x="([0-9.]+)" y="([0-9.]+)"[^>]*/>',
        svg,
    )
    if match.group(1) in eaten
]
if len(cells) < 4:
    raise SystemExit("Could not find enough eaten contribution cells")
cells.sort()
times = [cell[0] for cell in cells]

def at(fraction):
    return times[round((len(times) - 1) * fraction)]

colors = [
    (0.0, "#facc15"),
    (at(0.20), "#f59e0b"),
    (at(0.40), "#fb7185"),
    (at(0.65), "#c026d3"),
    (at(0.85), "#9333ea"),
    (100.0, "#7c3aed"),
]
color_frames = "".join(
    f"{moment:.2f}%{{fill:{color};filter:drop-shadow(0 0 4px {color})}}"
    for moment, color in colors
)
css = ["@keyframes snakeColor{" + color_frames + "}"]
css.append(
    ".food-pulse{fill:none;stroke:#f59e0b;stroke-width:2;opacity:0;"
    "pointer-events:none;transform-box:fill-box;transform-origin:center;"
    "animation:none linear 26000ms infinite}"
)
circles = []
for index in range(16):
    moment, x, y = cells[round((len(cells) - 1) * (index + 0.5) / 16)]
    before = max(0.0, moment - 0.55)
    after = min(100.0, moment + 0.9)
    css.append(
        f"@keyframes food{index}{{"
        f"0%,{before:.2f}%{{opacity:0;transform:scale(.15)}}"
        f"{moment:.2f}%{{opacity:.9;transform:scale(.55)}}"
        f"{after:.2f}%,100%{{opacity:0;transform:scale(1.5)}}"
        f"}}.food-pulse.food{index}{{animation-name:food{index}}}"
    )
    circles.append(
        f'<circle class="food-pulse food{index}" cx="{x:g}" cy="{y:g}" r="8"/>'
    )

duration = re.search(r"\b[0-9]+ms\b", svg)
if duration is None:
    raise SystemExit("Could not find snk animation duration")
svg = svg.replace(duration.group(), "26000ms")
svg = svg.replace(
    ".s{shape-rendering:geometricPrecision;",
    ".s{stroke:#fff;stroke-width:.6px;shape-rendering:geometricPrecision;",
)
svg, count = re.subn(
    r"(\.s\.s[0-9]+\{[^{}]*animation-name:s[0-9]+)\}",
    r"\1,snakeColor}",
    svg,
)
if count < 4:
    raise SystemExit("Could not attach color animation to all snake segments")
svg = svg.replace("</style>", "".join(css) + "</style>", 1)
svg = svg.replace("</svg>", "".join(circles) + "</svg>", 1)
svg_path.write_text(svg, encoding="utf-8")
print(f"Styled {len(cells)} contribution cells and {count} snake segments")
